# Site settings
title: Jekyll for Web Designers
description: "venkat chiluvuri's blog where he posts about new technologies and provides resources"
baseurl: "" 
url: "http://cvsnraju.github.io" 
tagline: Venkat Chiluvuri blog

# Build settings
markdown: kramdown
kramdown:
    auto_ids: false
plugins: [jekyll-paginate]    
paginate: 4
paginate_path: '/blog/page:num/'
permalink: /blog/:title
