# Site settings
title: Venkata Chiluvuri
description: "Venkata Chiluvuri blog, where he posts about new technologies and provides resources"
baseurl: "" 
url: "https://cvsnraju.github.io" 
tagline: If it is so simple, why haven't you done it yet?. 

# Build settings
markdown: kramdown
kramdown:
auto_ids: false
plugins: [jekyll-paginate]    
paginate: 4
paginate_path: '/blog/page:num/'
permalink: /blog/:title
